#  Name of workflow
name: Netlify Deploy

# When workflow is triggered
on:
  # push:
  #   tags:
  #     - "v*"
  push:
    branches:
      - main
      - netlify-deploy

  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

# Jobs to carry out
jobs:
  deploy:
    # Operating system to run job on
    runs-on: ubuntu-latest
    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      # Install NodeJS
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          cd frontend
          npm i
          npm run build
      # Deploy to Netlify using our production secrets
      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=frontend/build/ --functions=functions --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}